### ISSUE TITLE
Move the "service contacts" question after list of documents is fully gathered

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-EFSPIntegration#117]

**Comment by BryceStevenWilley** [comment]
Unfortunately, this can't be done with more refactoring and IMO making the docassemble more complicated. We use `service_contacts` to see if we can automatically fill in the document's `filing_action`, which is `efile`, `serve`, or `efile and serve`. If there are no service contacts, there's only one valid option so we don't ask it, but either way we do need to know if they plan to serve the documents before we can finish gathering the list of documents.

Given how docassemble gathers lists of things, there's no easy way to gather all of the documents first, and then go through again ensuring the `filing_action` is set that is modular and can be integrated into other interviews easily.
