### ISSUE TITLE
Is x.filing_parties truly meant to be per-document?

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-EFSPIntegration#119]
@BryceStevenWilley 

And if so, is it required for each document, or just the lead document?

**Comment by nonprofittechy** [comment]
explain_user_paying comes up in a weird place right now (from an earlier change I made). Just wondering how best to relocate it

**Comment by BryceStevenWilley** [comment]
Yeah, it's per document.

**Comment by nonprofittechy** [comment]
OK, I'm a bit confused about how this impacts fee calculations, but maybe it doesn't impact that at all.
