### ISSUE TITLE
Remove a case party from an existing case???

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-EFSPIntegration#126]
Mentioned in test SF4, but it is a very weird idea for someone to be able to delete a case party w/o a judge order.

**Comment by BryceStevenWilley** [comment]
Given that it's mentioned only in the cert step title and not actually in the steps for that test, and due to the fact that the Reference Guide specifically says:
>  A subsequent filing can be used to add parties to a case, or to add attorneys to existing parties; however, it cannot be used to edit existing party information or to change existing attorney assignments, including pro se

I think it's just poor writing.
