### ISSUE TITLE
Make a frontend for service only envelopes

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-EFSPIntegration#128]
An envelope that doesn't e-file anything, it is only used to serve the other party with something. Everything is the same as the e-filing interview, it just doesn't ultimately get e-filed, you call a different endpoint.

There are still fees associated with it.

We need to basically offer a choice at the end:

1. efile
2. serve the other party
3. both e-file and serve

this is a per-document choice.

**Comment by BryceStevenWilley** [comment]
I went with a simplified version of this, that should still probably change. It gives two choices: efile or serve, and if there are service contacts attached to the efiling, it does efile - and - serve. 

I'll iterate on this soon, likely before Tyler gets back to us on certification

**Comment by BryceStevenWilley** [comment]
Tyler got back to us quickly, so I got on this quickly. We should be good, still need to figure out how to get a unit test for this though.
