### ISSUE TITLE
Add some questions for `max_fee_amount`

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-EFSPIntegration#13]
When filing with Tyler, the clerk might tack on additional fees to a case that a user didn't add themselves properly (not sure what exact examples). Tyler includes a court setting that lets people give a maximum fee amount that they are willing to pay if the clerk has to change things. 

We should make some default questions to fill this variable (`max_fee_amount`), and either let authors use it (if it makes sense) or automatically see if the court supports it and ask it.

**Comment by nonprofittechy** [comment]
Feel free to triage if this isn't an MVP task--I can't tell if this will get tested or not

**Comment by nonprofittechy** [comment]
I will add some questions in a branch ready to get used--it looks like it's supported in the proxy server itself. It's not allowed by default.

Maybe check to see if any courts actually do allow it.

**Comment by nonprofittechy** [comment]
Appears that no Illinois court (even the test ones) have this turned on. Suspect it will be deprecated, or is only used in other states.

```
tyler_efm_codes=# select name from location where allowmaxfeeamount='True';
 name
------
(0 rows)
```

**Comment by BryceStevenWilley** [comment]
Can confirm that no courts on Stage for IL, MA, CA, IN, or TX have this either. So, going to mark this as used for now, with the revisit.
