### ISSUE TITLE
To pass tests, check if `PROSE_` env vars are set correctly

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-EFSPIntegration#218]
From the test results, it looks like the `PROSE_EMAIL` and `PROSE_PASSWORD` may be set incorrectly. [Either that or something is going wrong with that login. Or maybe the test was supposed to use the `TYLER` env vars instead, though the test description (pro se login) indicates otherwise.] Test: https://github.com/SuffolkLITLab/docassemble-EFSPIntegration/actions/runs/5612434136/job/15206157982

**Comment by BryceStevenWilley** [comment]
Those variables were not set incorrectly, it's definitely something wrong with the server availability. Closing this as I disabled Kiln tests for now, until https://github.com/SuffolkLITLab/ALKiln/pull/740 is integrated and there's more server consistency.
