### ISSUE TITLE
Error when adding an eCheck payment account

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-EFSPIntegration#23]
```
JAXBException occurred : unable to marshal type "tyler.efm.services.schema.common.ErrorType" as an element because it is missing an @XmlRootElement annotation. 
```

![image](https://user-images.githubusercontent.com/7645641/133705659-b5790f12-354c-42f0-97f3-a9928401af74.png)

**Comment by BryceStevenWilley** [comment]
Looks like I was mistakenly trying to send back the entire XML error object instead of just the error text (why Java needs there to be an XML root and it can't just serialize the object is beyond me).

Should be fixed now.
