### ISSUE TITLE
New payment accounts are named "my_name" - use a better default or customize up front

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-EFSPIntegration#24]

**Comment by BryceStevenWilley** [comment]
Should be an easy fix: change https://github.com/SuffolkLITLab/docassemble-EFSPIntegration/blob/d069983cd40568924177e2b455f8addf601b4782/docassemble/EFSPIntegration/data/questions/admin_interview.yml#L623 to take a python variable, and let the user provide that variable, probably on the New payment account screen: https://github.com/SuffolkLITLab/docassemble-EFSPIntegration/blob/d069983cd40568924177e2b455f8addf601b4782/docassemble/EFSPIntegration/data/questions/admin_interview.yml#L652

**Comment by BryceStevenWilley** [comment]
I think this is already fixed
