### ISSUE TITLE
Error when using get_filing

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-EFSPIntegration#29]
response_code: 500, data: {‘cause0’: ‘java.lang.NullPointerException: Cannot invoke “tyler.ecf.extensions.filingdetailquerymessage.ObjectFactory.createFilingDetailQueryMessageType()” because “this.detailObjFac” is null’, ‘message’: ‘java.lang.NullPointerException: Cannot invoke “tyler.ecf.extensions.filingdetailquerymessage.ObjectFactory.createFilingDetailQueryMessageType()” because “this.detailObjFac” is null’, ‘url’: ‘/filingreview/courts/adams/filings/abb2fb37-bf79-4a6c-a0da-d0d150878f8e’, ‘status’: ‘500’}
Press one of the following buttons:

**Comment by nonprofittechy** [comment]
This works now--the issue was that we needed to be granted permission on the Tyler side.

**Comment by BryceStevenWilley** [comment]
I don't think it was a permissions issue, it was an unrelated java bug that I pushed late yesterday.
