### ISSUE TITLE
Uploading a document should ultimately be required for most interactions with the filing interview

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-EFSPIntegration#42]
Some interactions with the filing interview don't require a document:

* add a service contact (already possible in the admin interview)
* Add a case party and attorney

For most kinds though, they are required. We may ultimately want to add additional validation for those cases so people can't do a nonsensical filing/document type matches the upload status.

**Comment by nonprofittechy** [comment]
@BryceStevenWilley has your thinking on this changed at all? I still wonder if just requiring someone always upload a document is the way to go.

**Comment by BryceStevenWilley** [comment]
No, I still think we need to force a document upload. In the XML schema document for the filing, the "LeadDocument" element has a minimum occurance of 1, so I don't even think the SOAP message will send without it. The document itself could be autogenerated though, maybe not for the any filing interview, but for specific interviews or procedures, we could just autogenerate a one sentence "I've added { person } as a service contact / party / attorney / etc." document.

**Comment by nonprofittechy** [comment]
Perfect. For MVP we will just make it required to upload at least one then.
