### ISSUE TITLE
Remove User Error

### ISSUE THREAD

**Issue by colarusso** [SuffolkLITLab/docassemble-EFSPIntegration#56]
When I try "Users" > "Remove user" I get an error: 

TypeError: 'NoneType' object is not iterable
In field index number 0

History
Needed definition of rm_user at 0.00000s
Tried to run block at 0.00007s

code: |
  resp = proxy_conn.remove_user(id=user_id) 
  del user_id
  rm_user = True

**Comment by nonprofittechy** [comment]
Any chance this was when your login token was invalid--after changing password? I can't reproduce this one.

Let us know what user id you tried to delete as well, if you recall. May be a permissions limit and we need to filter the options.

**Comment by nonprofittechy** [comment]
Closing this for now. We should do more tests of the whole checklist and this might resurface, but this may have been particular to not getting the re-login prompt after a password change.
