### ISSUE TITLE
Get All Users after changed pwd error

### ISSUE THREAD

**Issue by colarusso** [SuffolkLITLab/docassemble-EFSPIntegration#57]
When clicking "users" > "get all users" after changing my password, I get the following error: 

response_code: 401, error_msg: Authentication failed, invalid/expired authentication token or email/password combination, data: None

This error did not appear again after logging in with the new password.

**Comment by nonprofittechy** [comment]
I think this is actually a valid response for our certification test, but not ideal UX for production. We could redirect people to login after password change. Maybe defer for post certification though unless it also touches on the password expiration issue.

**Comment by BryceStevenWilley** [comment]
I think it does touch on the password expiration certification test, which says we need to:
> The system will respond with authorization error and _prompt to log in again._
