### ISSUE TITLE
Register - Get All Users Issue

### ISSUE THREAD

**Issue by colarusso** [SuffolkLITLab/docassemble-EFSPIntegration#58]
After registering a new user (Test McTesterson), and activating the account from the system-generated email, I did not see the user listed when visiting "users" > "get all users." This behavior persisted after restarting the interview and logging in again. FWIW, I confirmed that Test could login and they could. However, as an individual filer they could not access the list of all users. 

response_code: 422, error_msg: Operation not available for individual filers., data: None

Also, the user did not appear after logging in again as a firm admin subsequent to the account logging in, and was not visible in the dropdown of users to "Resend Other Activation Email."

**Comment by colarusso** [comment]
For completeness they didn't show up in the "Get User" drop down either.

**Comment by nonprofittechy** [comment]
Can you confirm if the new user was a pro se or a firm member? You shouldn't be able to view pro se users as a firm admin. You should be able to view firm admins and firm members.

**Comment by nonprofittechy** [comment]
I'm able to see firm members/admins when newly created--I'm assuming this one was a pro se user. Closing for now.
