### ISSUE TITLE
Update User vs. Update User Information

### ISSUE THREAD

**Issue by colarusso** [SuffolkLITLab/docassemble-EFSPIntegration#59]
The "Update User" button leads to a screen titled "Update User Information." Which wording is used in the certification? If it's not "Update User," we should probably update the button to reflect the cert docs.

**Comment by BryceStevenWilley** [comment]
Good point. The certification docs seem to use "Update User", "Update User Information", and "Change Information" interchangeability, but the API call itself is "Update User".
