### ISSUE TITLE
Add a picklist for party_id for use in attach service contact call

### ISSUE THREAD

**Issue by colarusso** [SuffolkLITLab/docassemble-EFSPIntegration#61]
I was asked for the party id at some point and wasn't able to proceed past that prompt as I didn't have one. Where do I find these?

**Comment by nonprofittechy** [comment]
This is probably listed somewhere in the get_case response?

**Comment by nonprofittechy** [comment]
It is in the get_case response. caseParticipant, person otherIdentification. If it's an attorney it's different than for a pro se person.

**Comment by nonprofittechy** [comment]
@BryceStevenWilley given the way we're handling partyID on the proxy server side for the filing interview now, is grabbing this GUID the right approach for independent `attach_service_contact` calls?

**Comment by nonprofittechy** [comment]
We don't care about "filings" at all--only real cases. so we need to do a case lookup of some kind.
