### ISSUE TITLE
Figure out a correct way to expose other party_types while still requiring at least one plaintiff/defendant

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-EFSPIntegration#66]
I think just force an edit screen/loop after users are gathered

**Comment by nonprofittechy** [comment]
Note: not sure this is relevant. At least when I chose "adoption" as the case type, I didn't see the plaintiff/defendant as available options. So I'm not positive the options are being filtered--unless the non-plaintiff/defendant options are only shown when plaintiff/defendant aren't applicable.

**Comment by nonprofittechy** [comment]
@BryceStevenWilley I think this is solved in the most flexible way for now. You mentioned filtering to only show plaintiff/defendant. I think we should change that to show all types now, right?

**Comment by BryceStevenWilley** [comment]
> You mentioned filtering to only show plaintiff/defendant. I think we should change that to show all types now, right?

Yeah, that's at https://github.com/SuffolkLITLab/docassemble-EFSPIntegration/blob/8dbe93736ce72d6e09494cc1372bdf83dcd0b9d5/docassemble/EFSPIntegration/data/questions/any_filing_interview.yml#L654, I'll remove it really quick.
