### ISSUE TITLE
For Cook County cross reference, should handle the pro se cross reference # on behalf of filers

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-EFSPIntegration#77]
See comments here: https://www.illinoislegalaid.org/legal-information/e-filing-tips-cook-county#Filing%20a%20document%20in%20an%20existing%20case

indicating that the cross reference number should be 99500 for a pro se. Is this stored in the code table anywhere, @BryceStevenWilley or just something pro se people need to know?

quick fix is adding the number on-screen for that page.

We should also default this number to being the attorney bar number if someone indicated that they have an attorney

**Comment by nonprofittechy** [comment]
See 
<html><body>
<a id=".Cross Reference Codes"><h4>Cross Reference Codes</h4>
		This call retrieves a listing of the valid case number cross reference type codes for a given court location. 
    

  |   |  
-- | -- | --
Version |   | 3.12
Required |   | Core functionality
Sample URL |   | https://court.tylerhost.net/CodeService/codes/crossreference/tyler:dc
Request Message Definition |   | N/A
Response Message Definition |   | genericode
XML Samples
DescriptionRequestResponseCross Reference CodesN/ACrossReferenceCodes | Cross Reference Codes | N/A | CrossReferenceCodes

Cross Reference Codes | N/A | CrossReferenceCodes
Inputs
FieldDescriptionNo Inputs | No Inputs

No Inputs
Outputs
FieldDescriptioncodeUnique EFM identifier for the codenameTextual description of the codecasetypeidIndicates that this cross reference type code is available for the specified case typeisdefaultIndicates that this cross reference type code is the default for the case typeisrequiredIndicates that this cross reference type code is required for the case typevalidationregexIndicates the regular expression used to validate the cross reference numbercustomvalidationfailuremessageA text string that contains a message to address a failure of the validation regex | code | Unique EFM identifier for the code | name | Textual description of the code | casetypeid | Indicates that this cross reference type code is available for the specified case type | isdefault | Indicates that this cross reference type code is the default for the case type | isrequired | Indicates that this cross reference type code is required for the case type | validationregex | Indicates the regular expression used to validate the cross reference number | customvalidationfailuremessage | A text string that contains a message to address a failure of the validation regex

code | Unique EFM identifier for the code
name | Textual description of the code
casetypeid | Indicates that this cross reference type code is available for the specified case type
isdefault | Indicates that this cross reference type code is the default for the case type
isrequired | Indicates that this cross reference type code is required for the case type
validationregex | Indicates the regular expression used to validate the cross reference number
customvalidationfailuremessage | A text string that contains a message to address a failure of the validation regex
 

</a>
</body>
</html>

which indicates that we can validate the cross reference number and possibly show people valid choices as well. Will experiment with cook:dr1 to see what it displays.

**Comment by BryceStevenWilley** [comment]
To clarify, that XML you posted is the list of possible cross references that can exist, like a type. The "99500" is the actual reference that the user is typing in, and is being checked against the "validationregex" in the XML. I think the staging version of that codes XML has the validation failure message of:
> Case type requires a 5-digit Case Cross Reference number and 
Case Cross Reference type "Cook County Attorney/Self-Represented Litigant Code", if self-represented
 use 99500.
 
 So it's probably safe to say that yeah, we could hardcode 99500. It's not anywhere we actually can extract from, but I'd be surprised if they change it. We could theoretically make sure the validation code always reads as such, and if it doesn't, fallback to making the user enter that number.

**Comment by nonprofittechy** [comment]
Maybe it's worth just showing that validation message? It doesn't look like an error message for this specific example, so that feels safe to do.
