### ISSUE TITLE
Case Lookup behavior?

### ISSUE THREAD

**Issue by colarusso** [SuffolkLITLab/docassemble-EFSPIntegration#80]
Not sure if this is a bug, but when using "Case Search" > "Find a case" and attempting to find a case by party, I get stuck on a prompt asking me for a "case tracking ID." Actually, if I enter "123" for that prompt and hit "next" I'm directed back to the admin page. The tracking ID question follows a request for a court ID, which followed a prompt for a party name. FWIW, I looked for "john doe." I don't know if the questions following the name request were only showing up because the name didn't return a result or if they are required. If the latter, it seemed odd that a case tracking ID would be needed to find a case by party name.  

When attempting to find a case by docket number and entering "00001" I was able to choose a court by ID (boone) and end with the following result (with no Next button): 

```
Results

{"cause1": "org.apache.cxf.binding.soap.SoapFault: Unknown exception occurred.", "cause0": "javax.xml.ws.soap.SOAPFaultException: Unknown exception occurred.", "message": "javax.xml.ws.soap.SOAPFaultException: Unknown exception occurred.", "url": "/cases/courts/boone/cases/00001", "status": "500"}

```
When attempting to find a case by tracking ID and entering "123" I was presented with a question, "Is this the case you were trying to find?" with no cases listed.

**Comment by nonprofittechy** [comment]
Not a great UX but not sure how to triage this yet. Directly entering the case tracking ID feels like a reasonable placeholder, but we should keep this open to continue to improve it.

I'll add to MVP for now but we might deprioritize

**Comment by nonprofittechy** [comment]
I added a screen that tells someone there are no results in #94
