### ISSUE TITLE
Check filing

### ISSUE THREAD

**Issue by colarusso** [SuffolkLITLab/docassemble-EFSPIntegration#82]
Note sure if it's a bug, but when using "Filings" > "Check filing" I am prompted first for a court ID, and then when I hit "Next" I am given a result without being asked to specify a case. Is this the intended behavior? 

```
Results of your request

response_code: 400, data: {‘required_vars’: [{‘name’: ‘users’, ‘description’: ‘the side of the matter that current person answering this interview is on’, ‘datatype’: ‘ALPeopleList’, ‘choices’: []}], ‘optional_vars’: [], ‘wrong_vars’: []}

```

**Comment by nonprofittechy** [comment]
Closing for now. You don't have access to the filing review permissions yet which I suspect triggered this error. It works fine for me.
