### ISSUE TITLE
Add validation of cross reference number

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-EFSPIntegration#86]
We're not validating cross reference numbers now. But we have a regex that we can use after doing an API call. Should probably add a generic function that resolves the validation regexes so it's easy to use as a question modifier.

https://court.tylerhost.net/CodeService/codes/crossreference/tyler:dc

<html><body>
<a id=".Cross Reference Codes">

Field | Description
-- | --
code | Unique EFM identifier for the code
name | Textual description of the code
casetypeid | Indicates that this cross reference type code is available for the specified case type
isdefault | Indicates that this cross reference type code is the default for the case type
isrequired | Indicates that this cross reference type code is required for the case type
validationregex | Indicates the regular expression used to validate the cross reference number
customvalidationfailuremessage | A text string that contains a message to address a failure of the validation regex

</a>
</body>
</html>

**Comment by BryceStevenWilley** [comment]
I think we are actually validation them now! It's https://github.com/SuffolkLITLab/docassemble-EFSPIntegration/blob/05844e053553d429c02890e4619f5f22d47f0e46/docassemble/EFSPIntegration/data/questions/any_filing_interview.yml#L485
