### ISSUE TITLE
Validation?

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-EFSPIntegration#87]
I opened #86 but @BryceStevenWilley do we need to do a general check for validation on various fields? Any other places I should be looking?

**Comment by BryceStevenWilley** [comment]
There are other ones we could check, there's a whole long list in the DataField section of the reference guide. Most (~40 or so) are already checked on the proxy side, and the rest are just things that have regexs. A quick check in the codes DB suggests that there are only 6 of those:
* Civil Case Damage Or Claim Initial Filing View
* Civil Case Damage Or Claim Subsequent Filing View
* ~Global Password Configuration~ already checking
* Set defaults on number of copies for optional services.
* PartyFilerID
* Party edit window: Phone Number

So we should prioritize those few ones.

**Comment by nonprofittechy** [comment]
Going to close this "meta" issue. I think the only crucial one left is phone numbers.
